<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!--macros-->
  <xacro:macro name="box_inertial" params="x y z mass *origin">
    <inertial>
      <mass value="${mass}" />
      <insert_block name="origin" />
      <inertia ixx="${0.0833333 * mass * (y*y + z*z)}" ixy="0.0" ixz="0.0"
        iyy="${0.0833333 * mass * (x*x + z*z)}" iyz="0.0"
        izz="${0.0833333 * mass * (x*x + y*y)}" />
    </inertial>
  </xacro:macro>

  <!--properties-->
  <property name="wall_depth" value="0.1" />
  <property name="wall_length" value="10" />
  <property name="wall_height" value="2.7" />
  <property name="gate_size" value="2.5" />

  <property name="M_PI" value="3.1415926535897931" />

  <!-- world link -->
  <link name="world" />

  <!-- wall_00 -->
  <link name="wall_00">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_00">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_00" type="fixed">
    <origin xyz="${-wall_length/2} 0 ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_00" />
  </joint>

  <!-- wall_01 -->
  <link name="wall_01">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_01">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_01" type="fixed">
    <origin xyz="0 ${-wall_length/2} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_01" />
  </joint>

  <!-- wall_02 -->
  <link name="wall_02">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_02">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_02" type="fixed">
    <origin xyz="${wall_length/2} 0 ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_02" />
  </joint>


  <!-- wall_03 -->
  <link name="wall_03">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length-gate_size}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length-gate_size} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length-gate_size} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_03">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_03" type="fixed">
    <origin xyz="${gate_size/2} ${wall_length/2} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_03" />
  </joint>


  <!-- wall_04 -->
  <link name="wall_04">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_04">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_04" type="fixed">
    <origin xyz="${wall_length} ${-wall_length/2} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_04" />
  </joint>

  <!-- wall_05 -->
  <link name="wall_05">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_05">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_05" type="fixed">
    <origin xyz="${(wall_length/2)+wall_length} 0 ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_05" />
  </joint>

  <!-- wall_06 -->
  <link name="wall_06">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_06">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_06" type="fixed">
    <origin xyz="${wall_length} ${wall_length/2} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_06" />
  </joint>


  <!-- wall_07 -->
  <link name="wall_07">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_07">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_07" type="fixed">
    <origin xyz="${-wall_length/2} ${wall_length} ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_07" />
  </joint>
    

  <!-- wall_08 -->
  <link name="wall_08">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_08">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_08" type="fixed">
    <origin xyz="0 ${(wall_length/2)+wall_length} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_08" />
  </joint>
    

  <!-- wall_09 -->
  <link name="wall_09">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_09">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_09" type="fixed">
    <origin xyz="${wall_length/2} ${wall_length} ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_09" />
  </joint>

  <!-- wall_10 -->
  <link name="wall_10">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_10">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_10" type="fixed">
    <origin xyz="${wall_length} ${(wall_length/2)+wall_length} ${wall_height/2}" rpy="0 0 ${90*M_PI/180}" />
    <parent link="world" />
    <child link="wall_10" />
  </joint>
    

  <!-- wall_11 -->
  <link name="wall_11">
    <xacro:box_inertial x="${wall_depth}" y="${wall_length}" z="${wall_height}" mass="5.0">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
      <material name="IPA/Grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${wall_depth} ${wall_length} ${wall_height}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="wall_11">
    <material>wall_floor_05</material>
  </gazebo>

  <joint name="joint_wall_11" type="fixed">
    <origin xyz="${(wall_length/2)+wall_length} ${wall_length} ${wall_height/2}" rpy="0 0 0" />
    <parent link="world" />
    <child link="wall_11" />
  </joint>
    
    
    




</robot>
